pool:
  vmImage: 'ubuntu-latest'

variables:
  system.debug: true

steps:
- task: Docker@2
  displayName: 'Docker login'
  inputs:
    containerRegistry: ajAcr3
    command: login
    
# - task: Docker@1
#   displayName: 'Docker login'
#   inputs:
#     containerregistrytype: Container Registry
#     dockerRegistryEndpoint: ajAcr3
#     command: login
    
- bash: |
   docker build -t ajacr3.azurecr.io/test:$(Build.BuildId) .
   docker push ajacr3.azurecr.io/test:$(Build.BuildId)
  displayName: 'Build and push - bash'
  
# - task: Docker@2
#   inputs:
#     containerRegistry: ajAcr3
#     repository: test
#   displayName: Docker@2 - Build and Push

# - task: DockerCompose@0
#   displayName: 'Run a Docker Compose command'
#   inputs:
#     containerregistrytype: 'Container Registry'
#     dockerComposeCommand: up
    
# - task: DockerCompose@0
#   displayName: 'Run a Docker Compose command'
#   inputs:
#     containerregistrytype: 'Container Registry'
#     dockerRegistryEndpoint: ajAcr3
#     dockerComposeCommand: up
